const TIMING_CONFIG = {
  CLIPBOARD_PASTE_DELAY: 100,
  CLIPBOARD_RESTORE_DELAY: 100,
  PASTE_TIMEOUT: 3000,
  HOTKEY_LOAD_DELAY: 1000,
  DEV_SERVER_RETRY_DELAY: 1000,
  DEV_SERVER_MAX_ATTEMPTS: 30,
  WINDOW_DRAG_FRAME_INTERVAL: 16,
  UPDATER_STARTUP_DELAY: 3000,
  UPDATER_INSTALL_DELAY: 100,
};

module.exports = { TIMING_CONFIG };
